# Generated by Django 3.2.15 on 2022-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='is_limit',
        ),
        migrations.AddField(
            model_name='food',
            name='is_limit',
            field=models.BooleanField(default=True, verbose_name='is_limit'),
        ),
    ]
