# Generated by Django 3.2.15 on 2022-08-29 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
    ]
