# Generated by Django 3.2.15 on 2022-09-05 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220905_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='days',
            field=models.IntegerField(choices=[(0, 'Everyday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Saturday'), (5, 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='days'),
        ),
    ]
