# Generated by Django 3.2.15 on 2022-08-31 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_auto_20220831_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='days',
            field=models.CharField(choices=[('0', 'Everyday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Saturday'), ('5', 'Sunday')], default='0', max_length=1, verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('0', 'Order'), ('1', 'Cancel'), ('2', 'Accept'), ('3', 'Paid'), ('4', 'Debt')], default=0, max_length=1, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('1', 'One Point'), ('2', 'Two Points'), ('3', 'Three Points'), ('4', 'Four Points'), ('5', 'Five Points')], default='5', max_length=1, verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['food'],
            },
        ),
    ]
