# Generated by Django 3.2.15 on 2022-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_orderitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Order'), ('1', 'Cancel'), ('2', 'Accept'), ('3', 'Paid'), ('4', 'Debt')], default=0, max_length=1),
        ),
    ]
