# Generated by Django 3.2.15 on 2022-08-29 05:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('food', '0003_alter_food_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['food', 'amount'], 'verbose_name': 'fooditem', 'verbose_name_plural': 'fooditems'},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='days',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='days',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
