# Generated by Django 3.2.15 on 2022-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_fooditem_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='days',
            field=models.IntegerField(choices=[(0, 'Everyday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Saturday'), (5, 'Sunday')], default=0, verbose_name='days'),
        ),
    ]
