# Generated by Django 3.2.15 on 2022-08-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20220829_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_limit',
            field=models.BooleanField(default=True, verbose_name='is_limit'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='amount'),
        ),
    ]
